### PR TITLE
fix installExtensionFromFolder

### PR DESCRIPTION
**Pull request by stell**
installExtensionFromFolder needed a pause cause it failed now and then when used in a workflow.
Also added vscode to ignore

### CODE REVIEW

**Comment by stell** [comment]
Can this be merged?

**Comment by richard67** [comment]
Have you noticed that the changes on GitHub show the complete `src/JoomlaBrowser.php` being changed because you have replaced all indentations with tabs by spaces?

Sorry, but this cannot be merged as it is.

**Comment by richard67** [comment]
Looks ok now.

**Comment by stell** [comment]
How about merging? It was good to go.

**Comment by Hackwar** [comment]
I've compared your PR with the current codebase and it seems as if all your changes are already part of JoomlaBrowser. So I'm closing this one for now. If you think something important is still missing, please open a new PR. Please keep in mind that the codeformating has to stay. You can see issues with the codestyle by opening the link to the build in drone.

**Comment by stell** [comment]
installExtensionFromFolder still needs a second and getConfig is also missing. So nothing of the PR is withing the current codebase.

**Comment by Hackwar** [comment]
Thank you for your work. I've give it some polish and merged it.

**Comment by stell** [comment]
Thanks for merging. Will take care around CS next time.

**Pull request merged**
