### PR TITLE
Added option for uploading extension file for client/server environments

### PR DESCRIPTION
**Pull request by jatitoam**

### CODE REVIEW

**Review by puneet0191 — APPROVED** [review]
Looks good to me, we could have provided the file path usage as a comment, to avoid the confusion of what we meant by _data folder, although it is clear. Thanks :smile:

**Comment by jatitoam** [comment]
Fixed (and added cs too)

**Comment by puneet0191** [comment]
Thanks :+1:

**Comment by puneet0191** [comment]
@yvesh  I will be merging this one, Please review..I have tested the code on my local machine.

**Comment by yvesh** [comment]
@puneet0191 sure, fine for me. I am not sure why we have to output the extension type (some are also missing), but rest looks fine :-)

**Comment by jatitoam** [comment]
About the extension, it's because Joomla outputs different messages depending on the extension types.  I can't recall if there are other messages out of those 3 so I think that's it.

I'm going to merge this since I'm ok with it too.

**Comment by jatitoam** [comment]
Nevermind, there are new cs errors :) can't merge even with the approval, so I'll fix

**Comment by jatitoam** [comment]
Replaced by #138

**Pull request closed without merging**
