### PR TITLE
Improved notices and stricts to support more PHP debug modes and inexisting pages

### PR DESCRIPTION
**Pull request by jatitoam**

### CODE REVIEW

**Comment by javigomez** [comment]
it would not work in my local:

screen shot 2015-08-04 at 20 43 31

**Comment by jatitoam** [comment]
That's odd... I did not remove any line but I just added new options https://github.com/joomla-projects/joomla-browser/pull/46/files#diff-676cca4b1f4fdd04825e9c7ae7b54691R326

**Comment by puneet0191** [comment]
What is the use case for this?, since we are already checking for 'Notice' keyword in page source

**Comment by jatitoam** [comment]
Not all PHP debuggers show the same... mine for example uses <b>Notice</b>: so the assert does not match

**Comment by javigomez** [comment]
ah! sorry I didn't notice that it was an addition. It has a lot of sense like this.

Thanks

**Pull request merged**
