### PR TITLE
Added back codestyle checks via Drone

### PR DESCRIPTION
**Pull request by jatitoam**
* It uses latest joomla/coding-standards for checking
* Added checks via Drone
* Fixed Codeception to v.2.3.7 as it's the latest supported (cc @puneet0191)

Important note: better squash this PR while merging, there was a good deal of tests while dealing with it

Enjoy !

### CODE REVIEW

**Comment by yvesh** [comment]
@jatitoam Any reason for Travis over our Drone? :-)

**Comment by jatitoam** [comment]
Just used to it.  Is Drone a preference now?

**Comment by yvesh** [comment]
@jatitoam as we got rid of travis totally in joomla 4 yes.. (We had and still have too many services)

**Comment by jatitoam** [comment]
True and good idea to merge them.  Can you please help me enable Drone for this repo so I can send a config file for it instead?

**Comment by yvesh** [comment]
@jatitoam okay done. Thanks!

**Comment by jatitoam** [comment]
Ok it's switched @yvesh :)
However I'm not sure what the Drone URL is to see the output so I tested it in a personal Drone in the meantime.

Can you please check and confirm? (and merge if you agree of course)

Also remember to require the Drone check for develop and master pushes once it's enabled

**Comment by jatitoam** [comment]
Heya :) just a friendly reminder, is it realistic to say that Drone will be enabled (and my code merged) if I solve conflicts?

**Comment by rdeutz** [comment]
I activated drone for this repo, so if you solve the conflicts it should work

**Review by rdeutz — APPROVED** [review]

**Comment by jatitoam** [comment]
Ok thanks, it's ready for merge now

**Review by puneet0191 — APPROVED** [review]
Thank you @jatitoam

**Comment by puneet0191** [comment]
@rdeutz can we merge this?

**Comment by puneet0191** [comment]
Thank you @jatitoam

**Comment by jatitoam** [comment]
:) np

**Pull request merged**
