### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by brianteeman**
You committed the last edit before I had finished ;) I have now

### CODE REVIEW

**Comment by wilsonge** [comment]
Jeeze merge things too slow. Then too fast. People should make their minds up :P :P

**Comment by Kubik-Rubik** [comment]
There is an "e" missing in *remov*. :-)

**Comment by brianteeman** [comment]
did a new PR for that

On 7 July 2015 at 15:40, Viktor Vogel <notifications@github.com> wrote:

> There is an "e" missing in *remov*. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla-projects/joomla-browser/pull/14#issuecomment-119224453>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Kubik-Rubik** [comment]
Thanks, already merged! ;-)

**Pull request merged**
