### PR TITLE
fixes the multi language install process.

### PR DESCRIPTION
**Pull request by svenbluege**
fixes the multi language install process. Again ;)

### CODE REVIEW

**Comment by astridx** [comment]
Is not this change also necessary in the develop branch?

**Comment by svenbluege** [comment]
If you apply the dev branch on Joomla 3.7: no. That would break the setup.

**Comment by astridx** [comment]
@svenbluege Thank you for your answer.

@all Shall we open a separate branch for 3.7 in this case?
I find it somewhat confusing. For me, the develp Branch is always the latest. Am I wrong?

**Comment by puneet0191** [comment]
@astridx Yes Develop Branch is always the latest, and I think these changes should also be applied to develop branch. We do not have any new 3.7.x release coming up, so I am sure we can merge these changes to develop now.

**Comment by astridx** [comment]
@puneet0191 Do we need to create a tag/releas for Joomla version 3.7 before we merge these changes?

**Comment by puneet0191** [comment]
Thanks @svenbluege

**Pull request merged**
