### PR TITLE
[Fix] Fix & improve for uninstallExtension

### PR DESCRIPTION
**Pull request by PetarT**
This changes fixes bugs with uninstall any type of extensions. Also allows to specific which extension type should be uninstalled.
PR refers to https://github.com/joomla-projects/joomla-browser/issues/119

### CODE REVIEW

**Comment by PetarT** [comment]
@yvesh feel free to check this one out when you have time :)

**Comment by puneet0191** [comment]
@PetarT Thanks for the PR :+1:

**Comment by astridx** [comment]
The test did not work for me.

My problems:

1.
There is no wantTo in Joomla-Browser. I think it is in Codeception/Actor.
I would change 
`$I->wantTo('Uninstall ' . $extensionName . ' ' . $type);
`
into
`$I->debug('Uninstall ' . $extensionName . ' ' . $type);
`

2.
In Weblinks we did the Adminlogin in the Cest-file. I think we should do it the same way here.

3.
`$I->click("Uninstall");
`
was not working for me. I do not know why.

But 
`$I->click(['class' => "icon-delete"]);
`
worked.

4.

This line did not working for me

`$I->pressKey(['id' => 'filter_search'], WebDriverKeys::ENTER);
`
I think it because the id 'filter_search' is the input textfield. We could not click it. I think

`$I->click(['class' => "icon-search"]);
`
would be OK

**So all-together this worked for me:**

```
    /**
     * Uninstall Extension based on a name
     *
     * @param   string  $extensionName  Is important to use a specific
     * @param   string  $type           Extension type (component/module/plugin/library etc)
     *
     * @return  void
     */
    public function uninstallExtension($extensionName, $type = 'Component')
    {
        $I = $this;

        if (!empty($type))
        {
            $I->debug('Uninstall ' . $extensionName . ' ' . $type);
        }
        else
        {
            $I->debug('Uninstall ' . $extensionName . ' extension');
        }

        //$I->doAdministratorLogin();
        $I->amOnPage('/administrator/index.php?option=com_installer&view=manage');

        if (!empty($type))
        {
            $I->click("//button[@class='btn hasTooltip js-stools-btn-filter']");
            $I->selectOptionInChosen('#filter_type', ucfirst($type));
        }

        $I->fillField('#filter_search', $extensionName);
        //$I->pressKey(['class' => 'icon-search'], WebDriverKeys::ENTER);
        $I->click(['class' => "icon-search"]);
        //$I->waitForElement('#manageList');
        $I->waitForElement(['id' => 'manageList'], 30);     
        $I->click("//input[@id='cb0']");
        //$I->click("Uninstall");
        $I->click(['class' => "icon-delete"]);
        $I->acceptPopup();

        if (!empty($type))
        {
            $I->see('Uninstalling the ' . strtolower($type) . ' was successful', '#system-message-container');
        }

        $I->fillField('#filter_search', $extensionName);
        //$I->pressKey(['id' => 'filter_search'], WebDriverKeys::ENTER);
        $I->click(['class' => "icon-search"]);
        $I->waitForText('There are no extensions installed matching your query.', 10, '.alert-no-items');
        $I->see('There are no extensions installed matching your query.', '.alert-no-items');
        $I->selectOptionInChosen('#filter_type', '- Select Type -');
        $I->debug('Extension successfully uninstalled');
    }




```

I used this testfile

```
    public function uninstallWeblinks(\AcceptanceTester $I)
    {
        $I->doAdministratorLogin();
        $I->comment('uninstall', 'Component');
        $I->uninstallExtension('Web Links');
        $I->doAdministratorLogout();
    }
```

**Comment by yvesh** [comment]
@PetarT can you look into the issues Astrid had?

**Comment by yvesh** [comment]
@PetarT closing that for now, if you want you can reopen it any time.

**Pull request closed without merging**
