### PR TITLE
[Fix] doFrontendLogout()

### PR DESCRIPTION
**Pull request by vortrixs**
When logging out in J3.7.x it redirects to `index.php/en/` instead of the user login view causing the test to fail.

To fix this we go back to the login view after logging out, then check if the login form is shown just as before

### CODE REVIEW

**Comment by vortrixs** [comment]
Not sure why my last commit got into this one, sorry about that, hope doesn't affect anything.

**Comment by javigomez** [comment]
Thanks for the provided update @vortrixs 
We would need to do a release for J3.7.

@puneet0191 could you take it?

**Comment by puneet0191** [comment]
I will take it. thanks @vortrixs

**Comment by puneet0191** [comment]
I have verified this patch, here is the result. 
image
It works fine, I am going to merge.

**Pull request merged**
