### PR TITLE
update h3

### PR DESCRIPTION
**Pull request by brianteeman**
The tag has been changed to h2 for the congratulations message in the installer see https://github.com/joomla/joomla-cms/pull/21447

### CODE REVIEW

**Comment by rdeutz** [comment]
looks ok to me, @puneet0191 ?

**Comment by brianteeman** [comment]
to be honest I would expect more failures that this one as there are tests for the multilingual stuff that should fail as they dont exist

**Comment by rdeutz** [comment]
its like a library not anything is used

**Review by puneet0191 — APPROVED** [review]

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
