### PR TITLE
Update JoomlaBrowser.php

### PR DESCRIPTION
**Pull request by astridx**
public function installJoomla() -> Text in select Option changed form 
English (United Kingdom)
to
English (en-GB)

### CODE REVIEW

**Comment by puneet0191** [comment]
Thanks for the PR :+1:  This change is done on Staging at the moment, we will release the new version along with Joomla.

**Comment by 810** [comment]
could we have a 3.7 branch, because now we get errors on travis. 3.7 will be released In 2 months. We can't wait for that.

or joomla-cms master need to staged j3.6.4 again. will create a issue for that.

**Comment by puneet0191** [comment]
@810 I will create a 3.7 branch. Thanks :+1:

**Comment by javigomez** [comment]
+1. Go ahead with this branch

**Comment by puneet0191** [comment]
Not sure if we will have another patch on 3.6.x, otherwise we can start merging changes for 3.7 on develop

**Comment by 810** [comment]
I have asked to revert the master branch on joomla, so that's also a way to fix this issue.

joomla hasn't got a main branch now

**Comment by yvesh** [comment]
@puneet0191 we probably will have more 3.6 releases, 3.6.4 was a security release only. Probably there will be another bug fix release before 3.7.. (which has been delayed a bit btw.)

**Comment by yvesh** [comment]
@javigomez @puneet0191 @810 As a more controversial question: Should we not focus on the Joomla! core steps / pages and allow them to be reusable by extensions, e.g. replace JoomlaBrowser with them in long term?

Maintaining two solutions, which have multiple overlaps will cost us resources we don't have. I really like JoomlaBrowser and use it in many projects.. But out of an outside view the question is, is it still needed?

**Comment by mbabker** [comment]
George mentioned elsewhere there will be no more 3.6 releases.  The next release will be 3.7 therefore it is appropriate that the branch has been merged to staging.  Any broken tooling therefore should be fixed.

**Comment by yvesh** [comment]
@mbabker Thanks for clarification. Everybody is telling different things nowadays..

**Comment by 810** [comment]
then we can merge this one.

**Comment by yvesh** [comment]
@astridx For which version did that change? Actually in current staging (3.7) it's still United Kingdom - or did i overlook something? :-)

**Comment by astridx** [comment]
I am not sure, but I think I tested it with 3.6.4.
@810 had asked to revert the master branch on joomla.
I have understood that the change has been undone. But I am not sure :) and I am not deep enough in github ...

**Comment by 810** [comment]
Our tests are failing again for 2 weeks, we should merge it. If its still works. @astridx could you test it again

**Comment by astridx** [comment]
I think the failing of the tests has another reason. 
If you change the language in the select box to Danish, the language on the page does not change.
Please have a look at this PR: https://github.com/joomla-projects/joomla-browser/pull/127

Are I am right? Should I close this PR?

**Comment by astridx** [comment]
I think this is reverted. That is why I close this.

**Pull request closed without merging**
