### PR TITLE
update selenium_v3.0.1.2

### PR DESCRIPTION
**Pull request by astridx**
I changed the random language to Spanish. Reason: If you change it to Danish the language in the installation dialog is not changed anymore. So the test failed because the text 'Generel konfiguration' could not be found.
Then I changed the syntax for clicking the toolbar button.
At last I add the method selectOptionInChosenWithTextField. This method fill the text field if a chosen field has one. With this change for me the test runs in Firefox.

### CODE REVIEW

**Comment by 810** [comment]
could you fix the codestyle issues

**Comment by astridx** [comment]
I fixed the codestyle issues

**Comment by 810** [comment]
tests are working for me.

**Comment by 810** [comment]
@yvesh could you merge this one

**Comment by jatitoam** [comment]
Agreed.  I'll merge it.

**Comment by astridx** [comment]
Thanks :)

**Comment by PhilETaylor** [comment]
da-DK ini file fixed in https://github.com/joomla/joomla-cms/pull/13544

**Pull request merged**
