### PR TITLE
Fixes failed test with latest Joomla 3.9 build. The Spanish locale is…

### PR DESCRIPTION
**Pull request by svenbluege**
… now named Español (España)

### CODE REVIEW

**Review by puneet0191 — APPROVED** [review]

**Comment by puneet0191** [comment]
Thank you! :+1:

**Review by yvesh — APPROVED** [review]

**Comment by svenbluege** [comment]
Stupid question but... do I need to do something because of the "Merging is blocked"-message here?

**Comment by puneet0191** [comment]
Nope, update you must follow this https://help.github.com/articles/about-commit-signature-verification/

**Comment by laoneo** [comment]
Guess this one can be closed as #181 got merged which basically does the same.

**Comment by puneet0191** [comment]
yeah, sure..thanks @svenbluege

**Pull request closed without merging**
